Copyright (c) Microsoft Corporation. All rights reserved.  
Licensed under the MIT License.

![Impressions](https://PixelServer20190423114238.azurewebsites.net/api/impressions/NotebookVM/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-with-automated-machine-learning-step.png)

# Azure Machine Learning Pipeline with AutoMLStep (Udacity Course 2)
This notebook demonstrates the use of AutoMLStep in Azure Machine Learning Pipeline.

## Introduction
In this example we showcase how you can use AzureML Dataset to load data for AutoML via AML Pipeline. 

If you are using an Azure Machine Learning Notebook VM, you are all set. Otherwise, make sure you have executed the [configuration](https://aka.ms/pl-config) before running this notebook.

In this notebook you will learn how to:
1. Create an `Experiment` in an existing `Workspace`.
2. Create or Attach existing AmlCompute to a workspace.
3. Define data loading in a `TabularDataset`.
4. Configure AutoML using `AutoMLConfig`.
5. Use AutoMLStep
6. Train the model using AmlCompute
7. Explore the results.
8. Test the best fitted model.

## Azure Machine Learning and Pipeline SDK-specific imports

In [1]:
import logging
import os
import csv

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets
import pkg_resources

import azureml.core
from azureml.core.experiment import Experiment
from azureml.core.workspace import Workspace
from azureml.train.automl import AutoMLConfig
from azureml.core.dataset import Dataset

from azureml.pipeline.steps import AutoMLStep

# Check core SDK version number
print("SDK version:", azureml.core.VERSION)

SDK version: 1.60.0

## Initialize Workspace
Initialize a workspace object from persisted configuration. Make sure the config file is present at .\config.json

In [2]:
ws = Workspace.from_config()
print(ws.name, ws.resource_group, ws.location, ws.subscription_id, sep = '\n')

quick-starts-ws-295275
aml-quickstarts-295275
westus2
d4ad7261-832d-46b2-b093-22156001df5b

## Create an Azure ML experiment
Let's create an experiment named "automlstep-classification" and a folder to hold the training scripts. The script runs will be recorded under the experiment in Azure.

The best practice is to use separate folders for scripts and its dependent files for each step and specify that folder as the `source_directory` for the step. This helps reduce the size of the snapshot created for the step (only the specific folder is snapshotted). Since changes in any files in the `source_directory` would trigger a re-upload of the snapshot, this helps keep the reuse of the step when there are no changes in the `source_directory` of the step.

*Udacity Note:* There is no need to create an Azure ML experiment, this needs to re-use the experiment that was already created

In [3]:
# Choose a name for the run history container in the workspace.
# NOTE: update these to match your existing experiment name
experiment_name = 'automl-bank'
project_folder = './pipeline-project'

experiment = Experiment(ws, experiment_name)
experiment

Experiment(Name: automl-bank,
Workspace: quick-starts-ws-295275)

### Create or Attach an AmlCompute cluster
You will need to create a [compute target](https://docs.microsoft.com/azure/machine-learning/service/concept-azure-machine-learning-architecture#compute-target) for your AutoML run. In this tutorial, you get the default `AmlCompute` as your training compute resource.

**Udacity Note** There is no need to create a new compute target, it can re-use the previous cluster

In [4]:
from azureml.core.compute import AmlCompute
from azureml.core.compute import ComputeTarget
from azureml.core.compute_target import ComputeTargetException

# NOTE: update the cluster name to match the existing cluster
# Choose a name for your CPU cluster
amlcompute_cluster_name = "automlcluster"

# Verify that cluster does not exist already
try:
    compute_target = ComputeTarget(workspace=ws, name=amlcompute_cluster_name)
    print('Found existing cluster, use it.')
except ComputeTargetException:
    compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_D2_V2',# for GPU, use "STANDARD_NC6"
                                                           #vm_priority = 'lowpriority', # optional
                                                           max_nodes=4)
    compute_target = ComputeTarget.create(ws, amlcompute_cluster_name, compute_config)

compute_target.wait_for_completion(show_output=True, min_node_count = 1, timeout_in_minutes = 10)
# For a more detailed view of current AmlCompute status, use get_status().

Found existing cluster, use it.
Succeeded
AmlCompute wait for completion finished

Minimum number of nodes requested have been provisioned

## Data

**Udacity note:** Make sure the `key` is the same name as the dataset that is uploaded, and that the description matches. If it is hard to find or unknown, loop over the `ws.datasets.keys()` and `print()` them.
If it *isn't* found because it was deleted, it can be recreated with the link that has the CSV

In [5]:
# Try to load the dataset from the Workspace. Otherwise, create it from the file
# NOTE: update the key to match the dataset name
found = False
key = "bankmarketing-dataset"
description_text = ""

if key in ws.datasets.keys(): 
        found = True
        dataset = ws.datasets[key] 

if not found:
        # Create AML Dataset and register it into Workspace
        example_data = 'https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv'
        dataset = Dataset.Tabular.from_delimited_files(example_data)        
        #Register Dataset in Workspace
        dataset = dataset.register(workspace=ws,
                                   name=key,
                                   description=description_text)


df = dataset.to_pandas_dataframe()
df.describe()

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000,32950.000000
mean,40.040212,257.335205,2.561730,962.174780,0.174780,0.076228,93.574243,-40.518680,3.615654,5166.859608
std,10.432313,257.331700,2.763646,187.646785,0.496503,1.572242,0.578636,4.623004,1.735748,72.208448
min,17.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.000000,179.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.000000,318.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

### Review the Dataset Result

You can peek the result of a TabularDataset at any range using `skip(i)` and `take(j).to_pandas_dataframe()`. Doing so evaluates only `j` records for all the steps in the TabularDataset, which makes it fast even against large datasets.

`TabularDataset` objects are composed of a list of transformation steps (optional).

In [6]:
dataset.take(5).to_pandas_dataframe()

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,57,technician,married,high.school,no,no,yes,cellular,may,mon,...,1,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,no
1,55,unknown,married,unknown,unknown,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
2,33,blue-collar,married,basic.9y,no,no,no,cellular,may,fri,...,1,999,1,failure,-1.8,92.893,-46.2,1.313,5099.1,no
3,36,admin.,married,high.school,no,no,no,telephone,jun,fri,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.967,5228.1,no
4,27,housemaid,married,high.school,no,yes,no,cellular,jul,fri,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,no

## Train
This creates a general AutoML settings object.
**Udacity notes:** These inputs must match what was used when training in the portal. `label_column_name` has to be `y` for example.

In [7]:
automl_settings = {
    "experiment_timeout_minutes": 20,
    "max_concurrent_iterations": 5,
    "primary_metric" : 'AUC_weighted'
}
automl_config = AutoMLConfig(compute_target=compute_target,
                             task = "classification",
                             training_data=dataset,
                             label_column_name="y",   
                             path = project_folder,
                             enable_early_stopping= True,
                             featurization= 'auto',
                             debug_log = "automl_errors.log",
                             **automl_settings
                            )

#### Create Pipeline and AutoMLStep

You can define outputs for the AutoMLStep using TrainingOutput.

In [8]:
from azureml.pipeline.core import PipelineData, TrainingOutput

ds = ws.get_default_datastore()
metrics_output_name = 'metrics_output'
best_model_output_name = 'best_model_output'

metrics_data = PipelineData(name='metrics_data',
                           datastore=ds,
                           pipeline_output_name=metrics_output_name,
                           training_output=TrainingOutput(type='Metrics'))
model_data = PipelineData(name='model_data',
                           datastore=ds,
                           pipeline_output_name=best_model_output_name,
                           training_output=TrainingOutput(type='Model'))

Create an AutoMLStep.

In [9]:
automl_step = AutoMLStep(
    name='automl_module',
    automl_config=automl_config,
    outputs=[metrics_data, model_data],
    allow_reuse=True)

In [10]:
from azureml.pipeline.core import Pipeline
pipeline = Pipeline(
    description="pipeline_with_automlstep",
    workspace=ws,    
    steps=[automl_step])

In [11]:
pipeline_run = experiment.submit(pipeline)

Created step automl_module [306914dd][8442668e-bf39-45b8-a5d4-1d3c489ac679], (This step will run and generate new outputs)
Submitted PipelineRun 9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748
Link to Azure Machine Learning Portal: https://ml.azure.com/runs/9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748?wsid=/subscriptions/d4ad7261-832d-46b2-b093-22156001df5b/resourcegroups/aml-quickstarts-295275/workspaces/quick-starts-ws-295275&tid=660b3398-b80e-49d2-bc5b-ac1dc93b5254

In [12]:
#from azureml.widgets import RunDetails
#RunDetails(pipeline_run).show()

ImportError: cannot import name 'Mapping' from 'collections' (/anaconda/envs/azureml_py38/lib/python3.10/collections/__init__.py)

In [13]:
pipeline_run.wait_for_completion()

PipelineRunId: 9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748
Link to Azure Machine Learning Portal: https://ml.azure.com/runs/9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748?wsid=/subscriptions/d4ad7261-832d-46b2-b093-22156001df5b/resourcegroups/aml-quickstarts-295275/workspaces/quick-starts-ws-295275&tid=660b3398-b80e-49d2-bc5b-ac1dc93b5254
PipelineRun Status: Running


StepRunId: 44593c48-4cf8-4ce1-ab0c-59e26ed1b985
Link to Azure Machine Learning Portal: https://ml.azure.com/runs/44593c48-4cf8-4ce1-ab0c-59e26ed1b985?wsid=/subscriptions/d4ad7261-832d-46b2-b093-22156001df5b/resourcegroups/aml-quickstarts-295275/workspaces/quick-starts-ws-295275&tid=660b3398-b80e-49d2-bc5b-ac1dc93b5254
StepRun( automl_module ) Status: Running

StepRun(automl_module) Execution Summary
=========================================
StepRun( automl_module ) Status: Finished

Warnings:
No scores improved over last 10 iterations, so experiment stopped early. This early stopping behavior can be disabled by setting enable_early_stopping = False in AutoMLConfig for notebook/python SDK runs.
{'runId': '44593c48-4cf8-4ce1-ab0c-59e26ed1b985', 'target': 'automlcluster', 'status': 'Completed', 'startTimeUtc': '2026-01-30T13:30:32.067976Z', 'endTimeUtc': '2026-01-30T13:52:18.63346Z', 'services': {}, 'warnings': [{'source': 'JasmineService', 'message': 'No scores improved over last 10 iterations, so experiment stopped early. This early stopping behavior can be disabled by setting enable_early_stopping = False in AutoMLConfig for notebook/python SDK runs.'}], 'properties': {'ContentSnapshotId': '2ecd3e1a-566e-42a2-abdc-263cf850620d', 'StepType': 'AutoMLStep', 'azureml.moduleid': '8442668e-bf39-45b8-a5d4-1d3c489ac679', 'azureml.moduleFamilyId': '785d0b13-932c-4abf-9b52-e00067ad580f', 'azureml.moduleName': 'automl_module', 'azureml.runsource': 'azureml.StepRun', 'azureml.nodeid': '306914dd', 'azureml.pipelinerunid': '9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748', 'azureml.pipeline': '9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748', 'azureml.rootpipelinerunid': '9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748', 'azureml.pipelineComponent': 'masterautomlcloud', 'num_iterations': '1000', 'training_type': 'TrainFull', 'acquisition_function': 'EI', 'metrics': 'accuracy', 'primary_metric': 'AUC_weighted', 'train_split': '0', 'MaxTimeSeconds': None, 'acquisition_parameter': '0', 'num_cross_validation': '', 'target': 'automlcluster', 'RawAMLSettingsString': None, 'AMLSettingsJsonString': '{"path": null, "name": "placeholder", "subscription_id": "d4ad7261-832d-46b2-b093-22156001df5b", "resource_group": "aml-quickstarts-295275", "workspace_name": "quick-starts-ws-295275", "region": "westus2", "compute_target": "automlcluster", "spark_service": null, "azure_service": null, "many_models": false, "pipeline_fetch_max_batch_size": 1, "enable_batch_run": false, "enable_parallel_run": false, "num_procs": null, "enable_run_restructure": false, "start_auxiliary_runs_before_parent_complete": false, "enable_code_generation": true, "force_curated_environment": false, "iterations": 1000, "primary_metric": "AUC_weighted", "task_type": "classification", "positive_label": null, "data_script": null, "test_size": 0.0, "test_include_predictions_only": false, "validation_size": 0.0, "n_cross_validations": null, "y_min": null, "y_max": null, "num_classes": null, "featurization": "auto", "_ignore_package_version_incompatibilities": false, "is_timeseries": false, "max_cores_per_iteration": 1, "max_concurrent_iterations": 5, "iteration_timeout_minutes": null, "mem_in_mb": null, "enforce_time_on_windows": false, "experiment_timeout_minutes": 20, "experiment_exit_score": null, "partition_column_names": null, "whitelist_models": null, "blacklist_algos": null, "supported_models": ["DecisionTree", "LightGBM", "GradientBoosting", "MultinomialNaiveBayes", "ExtremeRandomTrees", "BernoulliNaiveBayes", "LogisticRegression", "TabnetClassifier", "TensorFlowDNN", "SGD", "SVM", "RandomForest", "TensorFlowLinearClassifier", "LinearSVM", "XGBoostClassifier", "AveragedPerceptronClassifier", "KNN"], "private_models": [], "auto_blacklist": true, "blacklist_samples_reached": false, "exclude_nan_labels": true, "verbosity": 20, "_debug_log": "automl_errors.log", "show_warnings": false, "model_explainability": true, "service_url": null, "sdk_url": null, "sdk_packages": null, "enable_onnx_compatible_models": false, "enable_split_onnx_featurizer_estimator_models": false, "vm_type": "Standard_DS3_v2", "telemetry_verbosity": 20, "send_telemetry": true, "enable_dnn": false, "scenario": "AutoML", "environment_label": null, "save_mlflow": false, "enable_categorical_indicators": false, "force_text_dnn": false, "enable_feature_sweeping": true, "enable_early_stopping": true, "early_stopping_n_iters": 10, "arguments": null, "dataset_id": null, "hyperdrive_config": null, "validation_dataset_id": null, "run_source": null, "metrics": null, "enable_metric_confidence": false, "enable_ensembling": true, "enable_stack_ensembling": true, "ensemble_iterations": 15, "enable_tf": false, "enable_subsampling": null, "subsample_seed": null, "enable_nimbusml": false, "enable_streaming": false, "force_streaming": false, "track_child_runs": true, "n_best_runs": 1, "allowed_private_models": [], "label_column_name": "y", "weight_column_name": null, "cv_split_column_names": null, "enable_local_managed": false, "_local_managed_run_id": null, "cost_mode": 1, "lag_length": 0, "metric_operation": "maximize", "preprocess": true}', 'DataPrepJsonString': '{\\"training_data\\": {\\"datasetId\\": \\"2c471bf8-7633-490a-82c6-24f9bd0e7105\\"}, \\"datasets\\": 0}', 'EnableSubsampling': 'False', 'runTemplate': 'AutoML', 'Orchestrator': 'AutoML', 'ClientType': 'Others', 'PlatformVersion': 'DPV1', '_aml_system_scenario_identification': 'Remote.Parent', 'root_attribution': 'azureml.StepRun', 'snapshotId': '2ecd3e1a-566e-42a2-abdc-263cf850620d', 'SetupRunId': '44593c48-4cf8-4ce1-ab0c-59e26ed1b985_setup', 'SetupRunContainerId': 'dcid.44593c48-4cf8-4ce1-ab0c-59e26ed1b985_setup', 'ClientSdkVersion': '1.61.0', 'FeaturizationRunJsonPath': 'featurizer_container.json', 'FeaturizationRunId': '44593c48-4cf8-4ce1-ab0c-59e26ed1b985_featurize', 'ProblemInfoJsonString': '{"dataset_num_categorical": 0, "is_sparse": true, "subsampling": false, "has_extra_col": true, "dataset_classes": 2, "dataset_features": 132, "dataset_samples": 29655, "single_frequency_class_detected": false}', 'ModelExplainRunId': '44593c48-4cf8-4ce1-ab0c-59e26ed1b985_ModelExplain'}, 'inputDatasets': [{'dataset': {'id': '2c471bf8-7633-490a-82c6-24f9bd0e7105'}, 'consumptionDetails': {'type': 'RunInput', 'inputName': 'training_data', 'mechanism': 'Direct'}}], 'outputDatasets': [], 'logFiles': {'logs/azureml/executionlogs.txt': 'https://mlstrg295275.blob.core.windows.net/azureml/ExperimentRun/dcid.44593c48-4cf8-4ce1-ab0c-59e26ed1b985/logs/azureml/executionlogs.txt?sv=2019-07-07&sr=b&sig=8Nh0fCMbs57bCAwam5l5C5bbIN1DZfHLXNF55v%2FXuSY%3D&skoid=774a88a5-f934-4460-ad79-83d5c9d39677&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2026-01-30T12%3A28%3A03Z&ske=2026-02-01T12%3A38%3A03Z&sks=b&skv=2019-07-07&st=2026-01-30T13%3A38%3A08Z&se=2026-01-30T21%3A48%3A08Z&sp=r', 'logs/azureml/stderrlogs.txt': 'https://mlstrg295275.blob.core.windows.net/azureml/ExperimentRun/dcid.44593c48-4cf8-4ce1-ab0c-59e26ed1b985/logs/azureml/stderrlogs.txt?sv=2019-07-07&sr=b&sig=5A2uoPzbc5pr4hnBS%2F7md75cZEa4RMqyKn0kWMwF0dY%3D&skoid=774a88a5-f934-4460-ad79-83d5c9d39677&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2026-01-30T12%3A28%3A03Z&ske=2026-02-01T12%3A38%3A03Z&sks=b&skv=2019-07-07&st=2026-01-30T13%3A38%3A08Z&se=2026-01-30T21%3A48%3A08Z&sp=r', 'logs/azureml/stdoutlogs.txt': 'https://mlstrg295275.blob.core.windows.net/azureml/ExperimentRun/dcid.44593c48-4cf8-4ce1-ab0c-59e26ed1b985/logs/azureml/stdoutlogs.txt?sv=2019-07-07&sr=b&sig=8D6tn%2F7X8rsT8dCWT0I00eO7pRcMIQVTxyD9aXVmgbs%3D&skoid=774a88a5-f934-4460-ad79-83d5c9d39677&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2026-01-30T12%3A28%3A03Z&ske=2026-02-01T12%3A38%3A03Z&sks=b&skv=2019-07-07&st=2026-01-30T13%3A38%3A08Z&se=2026-01-30T21%3A48%3A08Z&sp=r'}, 'submittedBy': 'ODL_User 295275'}



PipelineRun Execution Summary
==============================
PipelineRun Status: Finished
{'runId': '9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748', 'status': 'Completed', 'startTimeUtc': '2026-01-30T13:30:17.017435Z', 'endTimeUtc': '2026-01-30T13:52:48.133516Z', 'services': {}, 'properties': {'azureml.runsource': 'azureml.PipelineRun', 'runSource': 'SDK', 'runType': 'SDK', 'azureml.parameters': '{}', 'azureml.continue_on_step_failure': 'False', 'azureml.continue_on_failed_optional_input': 'True', 'azureml.pipelineComponent': 'pipelinerun', 'azureml.pipelines.stages': '{"Initialization":null,"Execution":{"StartTime":"2026-01-30T13:30:17.3747798+00:00","EndTime":"2026-01-30T13:52:47.9893438+00:00","Status":"Finished"}}'}, 'inputDatasets': [], 'outputDatasets': [], 'logFiles': {'logs/azureml/executionlogs.txt': 'https://mlstrg295275.blob.core.windows.net/azureml/ExperimentRun/dcid.9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748/logs/azureml/executionlogs.txt?sv=2019-07-07&sr=b&sig=drgNIkySXwy9lWZBezz0ZXHvl5QeaPJ82TP8UcG%2BYOw%3D&skoid=774a88a5-f934-4460-ad79-83d5c9d39677&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2026-01-30T12%3A28%3A03Z&ske=2026-02-01T12%3A38%3A03Z&sks=b&skv=2019-07-07&st=2026-01-30T13%3A42%3A49Z&se=2026-01-30T21%3A52%3A49Z&sp=r', 'logs/azureml/stderrlogs.txt': 'https://mlstrg295275.blob.core.windows.net/azureml/ExperimentRun/dcid.9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748/logs/azureml/stderrlogs.txt?sv=2019-07-07&sr=b&sig=m%2BLnmPBnMM4Lf7IaiXz9Cqx7Rr5PHKbCrP62p51P2lI%3D&skoid=774a88a5-f934-4460-ad79-83d5c9d39677&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2026-01-30T12%3A28%3A03Z&ske=2026-02-01T12%3A38%3A03Z&sks=b&skv=2019-07-07&st=2026-01-30T13%3A42%3A49Z&se=2026-01-30T21%3A52%3A49Z&sp=r', 'logs/azureml/stdoutlogs.txt': 'https://mlstrg295275.blob.core.windows.net/azureml/ExperimentRun/dcid.9e60ef3d-6ad2-42bc-a2c0-e166d8e2a748/logs/azureml/stdoutlogs.txt?sv=2019-07-07&sr=b&sig=1HKqPC2PmxflIV7c%2Fge1JavCOWL%2BNnVejXwz8VfH9Cw%3D&skoid=774a88a5-f934-4460-ad79-83d5c9d39677&sktid=660b3398-b80e-49d2-bc5b-ac1dc93b5254&skt=2026-01-30T12%3A28%3A03Z&ske=2026-02-01T12%3A38%3A03Z&sks=b&skv=2019-07-07&st=2026-01-30T13%3A42%3A49Z&se=2026-01-30T21%3A52%3A49Z&sp=r'}, 'submittedBy': 'ODL_User 295275'}

'Finished'

## Examine Results

### Retrieve the metrics of all child runs
Outputs of above run can be used as inputs of other steps in pipeline. In this tutorial, we will examine the outputs by retrieve output data and running some tests.

In [14]:
metrics_output = pipeline_run.get_pipeline_output(metrics_output_name)
num_file_downloaded = metrics_output.download('.', show_progress=True)

Downloading azureml/44593c48-4cf8-4ce1-ab0c-59e26ed1b985/metrics_data
Downloaded azureml/44593c48-4cf8-4ce1-ab0c-59e26ed1b985/metrics_data, 1 files out of an estimated total of 1

In [15]:
import json
with open(metrics_output._path_on_datastore) as f:
    metrics_output_result = f.read()
    
deserialized_metrics_output = json.loads(metrics_output_result)
df = pd.DataFrame(deserialized_metrics_output)
df

,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_5,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_4,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_7,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_1,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_2,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_8,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_3,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_0,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_6,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_10,...,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_45,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_41,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_38,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_40,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_43,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_46,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_48,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_53,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_44,44593c48-4cf8-4ce1-ab0c-59e26ed1b985_52
AUC_weighted,[0.9388252597495217],[0.9225368484033442],[0.9290011799639528],[0.942328104073932],[0.8958056634564979],[0.941632999720291],[0.8782909787402727],[0.9446537630106308],[0.9247722039763119],[0.9237121814143637],...,[0.930295528177428],[0.9349838935846638],[0.927933284801064],[0.5],[0.9434728728695352],[0.9441721450707331],[0.9378096942281794],[0.9460504550363342],[0.9360832791513151],[0.9473665686759395]
f1_score_micro,[0.908649468892261],[0.9071320182094081],[0.9119878603945372],[0.9116843702579667],[0.9001517450682853],[0.9104704097116844],[0.8880121396054628],[0.9101669195751139],[0.7918057663125948],[0.9083459787556905],...,[0.9113808801213961],[0.9059180576631259],[0.8030349013657057],[0.8880121396054628],[0.9144157814871017],[0.9110773899848255],[0.9080424886191198],[0.9144157814871017],[0.9089529590288316],[0.91350531107739]
matthews_correlation,[0.47077965319103915],[0.42149687086703563],[0.47805766735773875],[0.52924365161229],[0.33340661446628406],[0.5016093372462171],[0.05255258421502397],[0.5216286298277554],[0.4837997244507513],[0.444201567492641],...,[0.45490452435707335],[0.4762071323693735],[0.5071411715737993],[0.0],[0.5414091775476605],[0.5186343797812246],[0.49542618619505285],[0.5354351023345689],[0.503208212781036],[0.5071384791911904]
precision_score_micro,[0.908649468892261],[0.9071320182094081],[0.9119878603945372],[0.9116843702579667],[0.9001517450682853],[0.9104704097116844],[0.8880121396054628],[0.9101669195751139],[0.7918057663125948],[0.9083459787556905],...,[0.9113808801213961],[0.9059180576631259],[0.8030349013657057],[0.8880121396054628],[0.9144157814871017],[0.9110773899848255],[0.9080424886191198],[0.9144157814871017],[0.9089529590288316],[0.91350531107739]
recall_score_macro,[0.693976256235563],[0.6457565754741621],[0.6863829010812322],[0.7477868729473351],[0.5932768914155307],[0.7210524463412782],[0.5035523954009191],[0.7445642005975768],[0.8531718246095653],[0.6653862112783807],...,[0.6599902379748336],[0.7102002974916967],[0.8677833719553874],[0.5],[0.7516930722964099],[0.7379720550452258],[0.7232377877435643],[0.7445882814945717],[0.7284869601942773],[0.7144723412374246]
AUC_micro,[0.9779290367296751],[0.9732255383035407],[0.9758368429657296],[0.9783641467160662],[0.9671371301070044],[0.9790036405000448],[0.9632521800401124],[0.9795361989126856],[0.9027457337530308],[0.9741933909150988],...,[0.9760537532150843],[0.9769563945924413],[0.9220643776725207],[0.8880121396054628],[0.9792886172777532],[0.9793347625155142],[0.9775107821894118],[0.9801326790718451],[0.9771997393392758],[0.9804761433265557]
accuracy,[0.908649468892261],[0.9071320182094081],[0.9119878603945372],[0.9116843702579667],[0.9001517450682853],[0.9104704097116844],[0.8880121396054628],[0.9101669195751139],[0.7918057663125948],[0.9083459787556905],...,[0.9113808801213961],[0.9059180576631259],[0.8030349013657057],[0.8880121396054628],[0.9144157814871017],[0.9110773899848255],[0.9080424886191198],[0.9144157814871017],[0.9089529590288316],[0.91350531107739]
AUC_macro,[0.9388252597495217],[0.922536848403344],[0.9290011799639528],[0.942328104073932],[0.8958056634564979],[0.941632999720291],[0.8782909787402726],[0.9446537630106308],[0.924772203976312],[0.9237121814143637],...,[0.9302955281774281],[0.9349838935846637],[0.927933284801064],[0.5],[0.9434728728695352],[0.944172145070733],[0.9378096942281794],[0.9460504550363343],[0.9360832791513152],[0.9473665686759396]
precision_score_weighted,[0.8973758906640772],[0.8930395334907932],[0.9005211086889047],[0.9067326786550023],[0.8827113977984437],[0.9021040535657128],[0.8451880573078699],[0.9051980543721705],[0.9166498470928354],[0.8950256468849379],...,[0.8995772735606997],[0.8969603334729989],[0.921129786749879],[0.788565560086672],[0.9092432341499307],[0.9048603955518554],[0.9004776478501716],[0.9082858447415418],[0.9019212790133414],[0.9041211076106344]
average_precision_score_macro,[0.8006349647033797],[0.7729463087908554],[0.8044713126721892],[0.8028233128807174],[0.7318788824494502],[0.8161730247772492],[0.7371547652592039],[0.8171134643523112],[0.7836605247909965],[0.7841343649033216],...,[0.803947852388421],[0.7986082345114851],[0.7870006903706823],[0.5],[0.8130250782253756],[0.8120855425982273],[0.8027104987797389],[0.8211334990722459],[0.8059777754621449],[0.8260362810572801]
norm_macro_recall,[0.38795251247112605],[0.2915131509483242],[0.37276580216246447],[0.4955737458946703],[0.1865537828310615],[0.44210489268255637],[0.007104790801838234],[0.48912840119515355],[0.7063436492191306],[0.3307724225567614],...,[0.31998047594966716],[0.4204005949833933],[0.7355667439107747],[0.0],[0.5033861445928198],[0.47594411009045157],[0.4464755754871286],[0.48917656298914336],[0.45697392038855456],[0.4289446824748493]
weighted_accuracy,[0.9619470207827714],[0.9720244705544736],[0.9679994692811393],[0.952375685487909],[0.9763404704059276],[0.9574977663473424],[0.9834630946313351],[0.9512815952194833],[0.7765702339612472],[0.9686663170697974],...,[0.9737943765645773],[0.954509483437858],[0.7869596075347821],[0.9843450583187134],[0.9548154286043442],[0.9540547622302472],[0.9539244969639455],[0.9565793559791012],[0.9537577850167812],[0.9629198137379152]
log_loss,[0.20462013175825502],[0.22090578349014284],[0.21382270165851136],[0.18692041784468305],[0.2431839925136322],[0.19932096535538657],[0.26235025127384237],[0.17851374134751752],[0.389832627581263],[0.21235370304099976],...,[0.6270449236400996],[0.1927321744818329],[0.3732482504240204],[0.3506525729212214],[0.18132646807082636],[0.1798535905397013],[0.20133969511676028],[0.19837997175177324],[0.2027216098242052],[0.18341639024804532]
recall_score_weighted,[0.908649468892261],[0.9071320182094081],[0.9119878603945372],[0.9116843702579667],[0.9001517450682853],[0.9104704097116844],[0.8880121396054628],[0.9101669195751139],[0.7918057663125948],[0.9083459787556905],...,[0.9113808801213961],[0.9059180576631259],[0.8030349013657057],[0.8880121396054628],[0.9144157814871017],[0.9110773899848255],[0.9080424886191198],[0.9144157814871017],[0.9089529590288316],[0.91350531107739]
average_precision_score_micro,[0.9789389178388146],[0.9744889524228721],[0.9760584861374465],[0.9793987356897456],[0.9684188522363333],[0.9799703642815116],[0.9622237645181168],[0.9805151927136845],[0.9100339616252012],[0.9752498455464272],...,[0.9766459224841124],[0.9780484501883515],[0.9273193660983552],[0.8445594902839405],[0.9802305566658834],[0.9803062878686369],[0.9785709152751796],[0.9810528229562928],[0.9782437790425166],[0.9813709479087148]
f1_score_weighted,[0.899959550454415],[0.8909573471197098],[0.9013350533065821],[0.9087877883554606],[0.8746567304785686],[0.9048597237768088],[0.8370804571152323],[0.9072831557855962],[0.8272976346559117],[0.8953324743236205],...,[0.8965841725295444],[0.9000970915329952],[0.8361970197628331],[0.8353395018439429],[0.9113076723159408],[0.9072716281032431],[0.9032835424144863],[0.9105642327263734],[0.9045847879480571],[0.9063557455531114]
precision_score_macro,[0.7856451172940535],[0.8047197211733953],[0.8065451980757572],[0.7826005666081467],[0.7979300898726163],[0.7845613466137928],[0.6943599878382487],[0.7781441711329087],[0.6656857633231223],[0.7982640315624551],...,[0.8233605513998398],[0.7697108848388048],[0.6748258536933281],[0.4440060698027314],[0.7911521311039829],[0.7825768973587429],[0.7748718176800369],[0.793034019312157],[0.7770601276271722],[0.799793245591095]
recall_score_micro,[0.908649468892261],[0.9071320182094081],[0.9119878603945372],[0.9116843702579667],[0.9001517450682853],[0.9104704097116844],[0.8880121396054628],[0.9101669195751139],[0.7918057663125948],[0.9083459787556905],...,[0.9113808801213961],[0.9059180576631259],[0.8030349013657057],[0.8880121396054628],[0.9144157814871017],[0.9110773899848255],[0.9080424886191198],[0.9144157814871017],[0.9089529590288316],[0.91350531107739]
average_precision_score_weighted,[0.9492172134275333],[0.9412516359851845],[0.9480633299225389],[0.950146970738567],[0.9289608872024528],[0.9529980385601647],[0.9255355389174825],[0.9535822261506017],[0.9438867188243628],[0.9437518530646575],...,[0.9485867248998229],[0.9483820478098488],[0.9443374547717386],[0.8011068409624182],[0.9524875074933626],[0.952392823977398],[0.9495969210036144],[0.954600528178806],[0.9501035972235514],[0.9558217419488405]
balanced_accuracy,[0.693976256235563],[0.6457565754741621],[0.6863829010812322],[0.7477868729473351],[0.5932768914155307],[0.7210524463412782],[0.5035523954009191],[0.7445642005975768],[0.8531718246095653],[0.6653862112783807],...,[0.6599902379748336],[0.7102002974916967],[0.8677833719553874],[0.5],[0.7516930722964099],[0.7379720550452258],[0.7232377877435643],[0.7445882814945717],[0.7284869601942773],[0.7144723412374246]
f1_score_macro,[0.7277105470003671],[0.6882189452748133],[0.7267246191790099],[0.763561123165114],[0.6267831475663812],[0.7472056145957435],[0.47831375703942075],[0.75980747558967],[0.6846046985649351],[0.70626695822815],...,[0.705497398224671],[0.7347169760358361],[0.6978682485695946],[0.4703423886834914],[0.7693891874827512],[0.7575588107000731],[0.745249445722951],[0.7657346712384026],[0.7494540455377727],[0.7473867103741525]

### Retrieve the Best Model

In [16]:
# Retrieve best model from Pipeline Run
best_model_output = pipeline_run.get_pipeline_output(best_model_output_name)
num_file_downloaded = best_model_output.download('.', show_progress=True)

Downloading azureml/44593c48-4cf8-4ce1-ab0c-59e26ed1b985/model_data
Downloaded azureml/44593c48-4cf8-4ce1-ab0c-59e26ed1b985/model_data, 1 files out of an estimated total of 1

In [17]:
import pickle

with open(best_model_output._path_on_datastore, "rb" ) as f:
    best_model = pickle.load(f)
best_model

PipelineWithYTransformations(Pipeline={'memory': None,
                                       'steps': [('datatransformer',
                                                  DataTransformer(enable_dnn=False, enable_feature_sweeping=True, working_dir='/mnt/batch/tasks/shared/LS_root/mounts/clusters/compute00/code/Users/odl_user_295275/starter_files')),
                                                 ('prefittedsoftvotingclassifier',
                                                  PreFittedSoftVotingClassifier(classification_labels=array([...nit_type': 'cpu'}), reg_alpha=0, reg_lambda=0.10416666666666667, subsample=0.7, tree_method='auto'))]))], flatten_transform=False, weights=[0.16666666666666666, 0.08333333333333333, 0.08333333333333333, 0.16666666666666666, 0.25, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333]))],
                                       'verbose': False},
                             y_transformer={},
                             y_transformer_name='LabelEncoder')

In [18]:
best_model.steps

[('datatransformer',
  DataTransformer(enable_dnn=False, enable_feature_sweeping=True, feature_sweeping_config={}, feature_sweeping_timeout=86400, featurization_config=None, force_text_dnn=False, is_cross_validation=False, is_onnx_compatible=False, task='classification')),
 ('prefittedsoftvotingclassifier',
  PreFittedSoftVotingClassifier(classification_labels=numpy.array([0, 1]), estimators=[('33', Pipeline(memory=None, steps=[('standardscalerwrapper', StandardScalerWrapper(copy=True, with_mean=False, with_std=False)), ('xgboostclassifier', XGBoostClassifier(booster='gbtree', colsample_bytree=0.7, eta=0.4, gamma=5, max_depth=6, max_leaves=0, n_estimators=100, n_jobs=1, objective='reg:logistic', problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=0, reg_alpha=1.7708333333333335, reg_lambda=1.5625, subsample=0.5, tree_method='auto'))], verbose=False)), ('0', Pipeline(memory=None, steps=[('maxabsscaler', MaxAbsScaler(copy=True)), ('lightgbmclassifier', LightGBMClassifier(min_data_in_leaf=20, n_jobs=1, problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=None))], verbose=False)), ('46', Pipeline(memory=None, steps=[('standardscalerwrapper', StandardScalerWrapper(copy=True, with_mean=False, with_std=True)), ('lightgbmclassifier', LightGBMClassifier(boosting_type='gbdt', colsample_bytree=0.7922222222222222, learning_rate=0.04211105263157895, max_bin=150, max_depth=6, min_child_weight=7, min_data_in_leaf=0.017249655172413794, min_split_gain=0.15789473684210525, n_estimators=400, n_jobs=1, num_leaves=245, problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=None, reg_alpha=0.05263157894736842, reg_lambda=1, subsample=0.3963157894736842))], verbose=False)), ('37', Pipeline(memory=None, steps=[('sparsenormalizer', Normalizer(copy=True, norm='max')), ('xgboostclassifier', XGBoostClassifier(booster='gbtree', colsample_bytree=1, eta=0.4, gamma=5, max_depth=10, max_leaves=0, n_estimators=200, n_jobs=1, objective='reg:logistic', problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=0, reg_alpha=0.9375, reg_lambda=2.3958333333333335, subsample=0.9, tree_method='auto'))], verbose=False)), ('15', Pipeline(memory=None, steps=[('maxabsscaler', MaxAbsScaler(copy=True)), ('lightgbmclassifier', LightGBMClassifier(boosting_type='goss', colsample_bytree=0.5944444444444444, learning_rate=0.026323157894736843, max_bin=310, max_depth=-1, min_child_weight=3, min_data_in_leaf=1e-05, min_split_gain=0.7894736842105263, n_estimators=50, n_jobs=1, num_leaves=131, problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=None, reg_alpha=0.3684210526315789, reg_lambda=1, subsample=1))], verbose=False)), ('43', Pipeline(memory=None, steps=[('standardscalerwrapper', StandardScalerWrapper(copy=True, with_mean=False, with_std=True)), ('lightgbmclassifier', LightGBMClassifier(boosting_type='gbdt', colsample_bytree=0.99, learning_rate=0.1, max_bin=20, max_depth=5, min_child_weight=7, min_data_in_leaf=0.07586448275862069, min_split_gain=0, n_estimators=800, n_jobs=1, num_leaves=68, problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=None, reg_alpha=0.631578947368421, reg_lambda=0.7368421052631579, subsample=0.05))], verbose=False)), ('36', Pipeline(memory=None, steps=[('standardscalerwrapper', StandardScalerWrapper(copy=True, with_mean=False, with_std=False)), ('xgboostclassifier', XGBoostClassifier(booster='gbtree', colsample_bytree=1, eta=0.3, gamma=0.01, max_depth=10, max_leaves=63, n_estimators=200, n_jobs=1, objective='reg:logistic', problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=0, reg_alpha=1.25, reg_lambda=2.1875, subsample=0.9, tree_method='auto'))], verbose=False)), ('7', Pipeline(memory=None, steps=[('standardscalerwrapper', StandardScalerWrapper(copy=True, with_mean=False, with_std=False)), ('xgboostclassifier', XGBoostClassifier(booster='gbtree', colsample_bytree=0.5, eta=0.3, gamma=0, max_depth=10, max_leaves=255, n_estimators=10, n_jobs=1, objective='reg:logistic', problem_info=ProblemInfo(gpu_training_param_dict={'processing_unit_type': 'cpu'}), random_state=0, reg_alpha=0, reg_lambda=0.10416666666666667, subsample=0.7, tree_method='auto'))], verbose=False))], flatten_transform=False, weights=[0.16666666666666666, 0.08333333333333333, 0.08333333333333333, 0.16666666666666666, 0.25, 0.08333333333333333, 0.08333333333333333, 0.08333333333333333]))]

### Test the Model
#### Load Test Data
For the test data, it should have the same preparation step as the train data. Otherwise it might get failed at the preprocessing step.

In [20]:
#dataset_test = Dataset.Tabular.from_delimited_files(path='https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv')
from azureml.core import Workspace, Dataset

subscription_id = "d4ad7261-832d-46b2-b093-22156001df5b"
resource_group = "aml-quickstarts-295275"
workspace_name = "quick-starts-ws-295275"

workspace = Workspace(subscription_id, resource_group, workspace_name)

dataset_test = Dataset.get_by_name(workspace, name="bankmarketing-dataset")
df_test = dataset_test.to_pandas_dataframe()
df_test = df_test[pd.notnull(df_test['y'])]

y_test = df_test['y']
X_test = df_test.drop(['y'], axis=1)

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

#### Testing Our Best Fitted Model

We will use confusion matrix to see how our model works.

In [21]:
from sklearn.metrics import confusion_matrix
ypred = best_model.predict(X_test)
cm = confusion_matrix(y_test, ypred)

In [22]:
# Visualize the confusion matrix
pd.DataFrame(cm).style.background_gradient(cmap='Blues', low=0, high=0.9)

## Publish and run from REST endpoint

Run the following code to publish the pipeline to your workspace. In your workspace in the portal, you can see metadata for the pipeline including run history and durations. You can also run the pipeline manually from the portal.

Additionally, publishing the pipeline enables a REST endpoint to rerun the pipeline from any HTTP library on any platform.

In [23]:
published_pipeline = pipeline_run.publish_pipeline(
    name="Bankmarketing Train", description="Training bankmarketing pipeline", version="1.0")

published_pipeline

Pipeline(Name: Bankmarketing Train,
Id: 080017e9-7a5d-4dc6-b731-0c107d359efa,
Status: Active,
Endpoint: https://westus2.api.azureml.ms/pipelines/v1.0/subscriptions/d4ad7261-832d-46b2-b093-22156001df5b/resourceGroups/aml-quickstarts-295275/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-295275/PipelineRuns/PipelineSubmit/080017e9-7a5d-4dc6-b731-0c107d359efa)

Authenticate once again, to retrieve the `auth_header` so that the endpoint can be used

In [24]:
from azureml.core.authentication import InteractiveLoginAuthentication

interactive_auth = InteractiveLoginAuthentication()
auth_header = interactive_auth.get_authentication_header()

Get the REST url from the endpoint property of the published pipeline object. You can also find the REST url in your workspace in the portal. Build an HTTP POST request to the endpoint, specifying your authentication header. Additionally, add a JSON payload object with the experiment name and the batch size parameter. As a reminder, the process_count_per_node is passed through to ParallelRunStep because you defined it is defined as a PipelineParameter object in the step configuration.

Make the request to trigger the run. Access the Id key from the response dict to get the value of the run id.

In [25]:
import requests

rest_endpoint = published_pipeline.endpoint
response = requests.post(rest_endpoint, 
                         headers=auth_header, 
                         json={"ExperimentName": "pipeline-rest-endpoint"}
                        )

In [26]:
try:
    response.raise_for_status()
except Exception:    
    raise Exception("Received bad response from the endpoint: {}\n"
                    "Response Code: {}\n"
                    "Headers: {}\n"
                    "Content: {}".format(rest_endpoint, response.status_code, response.headers, response.content))

run_id = response.json().get('Id')
print('Submitted pipeline run: ', run_id)

Submitted pipeline run:  650944dc-5240-4524-9edb-73907bf08a72

Use the run id to monitor the status of the new run. This will take another 10-15 min to run and will look similar to the previous pipeline run, so if you don't need to see another pipeline run, you can skip watching the full output.